# Generated by Django 5.0.1 on 2024-01-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('transcript', models.TextField()),
                ('hindi_transcript', models.TextField()),
                ('marathi_transcript', models.TextField()),
                ('tamil_transcript', models.TextField()),
                ('kannada_transcript', models.TextField()),
                ('telgu_transcript', models.TextField()),
                ('summary', models.TextField()),
                ('sentiment_positive', models.FloatField()),
                ('sentiment_negative', models.FloatField()),
                ('sentiment_neutral', models.FloatField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
