# Generated by Django 5.0.1 on 2024-01-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetfile',
            name='hindi_transcript',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='meetfile',
            name='kannada_transcript',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='meetfile',
            name='marathi_transcript',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='meetfile',
            name='sentiment_negative',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='meetfile',
            name='sentiment_neutral',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='meetfile',
            name='sentiment_positive',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='meetfile',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='meetfile',
            name='tamil_transcript',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='meetfile',
            name='telgu_transcript',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='meetfile',
            name='transcript',
            field=models.TextField(default=''),
        ),
    ]
